In [3]:
import nibabel as nib
import numpy as np
import os

path = "CF6028"
nii_path = "/home/cuixing/MDP/Data_Predict/Predicted_Result/50_Predict/" + path + ".nii.gz"

img = nib.load(nii_path)
data = img.get_fdata()  
data = data.astype(np.int16) 

# print all albel
unique_labels = np.unique(data)
print("Unique labels in the segmentation:", unique_labels)

Unique labels in the segmentation: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


## 1.Turn all the predict results into binary labels

In [13]:
import os
from glob import glob
import nibabel as nib
import numpy as np

TEST_DIR = "/home/cuixing/MDP/Data_Predict/Test_Data"
PRED_DIR = "/home/cuixing/MDP/Data_Predict/Predicted_Result/50_Predict"
DST_DIR = PRED_DIR

EXCLUDE_LABELS = (25, 26) # exclude the sturnum and costal cartilage

case_ids = sorted({os.path.basename(f).split('_')[0] for f in glob(os.path.join(TEST_DIR, "*.nii.gz"))})
os.makedirs(DST_DIR, exist_ok=True)

def find_pred(case):
    p = os.path.join(PRED_DIR, f"{case}.nii.gz")
    if os.path.exists(p):
        return p
    candidates = [f for f in glob(os.path.join(PRED_DIR, f"{case}_*.nii.gz")) if not f.endswith("_binary.nii.gz")]
    return sorted(candidates)[0] if candidates else None

ok = miss = 0
for case in case_ids:
    src = find_pred(case)
    if not src:
        print(f"[WARN] {case}: pred not found")
        miss += 1
        continue
    img = nib.load(src)
    data = img.get_fdata()
    mask = (data > 0) & (~np.isin(data, EXCLUDE_LABELS))
    bin_data = mask.astype(np.uint8)
    out_path = os.path.join(DST_DIR, f"{case}_binary.nii.gz")
    out_img = nib.Nifti1Image(bin_data, img.affine, img.header)
    out_img.set_data_dtype(np.uint8)
    nib.save(out_img, out_path)
    print(f"[OK] {case}: {src} -> {out_path}")
    ok += 1

print(f"done saved={ok} missing={miss}")


[OK] CF5008: /home/cuixing/MDP/Data_Predict/Predicted_Result/50_Predict/CF5008.nii.gz -> /home/cuixing/MDP/Data_Predict/Predicted_Result/50_Predict/CF5008_binary.nii.gz
[OK] CF5009: /home/cuixing/MDP/Data_Predict/Predicted_Result/50_Predict/CF5009.nii.gz -> /home/cuixing/MDP/Data_Predict/Predicted_Result/50_Predict/CF5009_binary.nii.gz
[OK] CF5015: /home/cuixing/MDP/Data_Predict/Predicted_Result/50_Predict/CF5015.nii.gz -> /home/cuixing/MDP/Data_Predict/Predicted_Result/50_Predict/CF5015_binary.nii.gz
[OK] CF5017: /home/cuixing/MDP/Data_Predict/Predicted_Result/50_Predict/CF5017.nii.gz -> /home/cuixing/MDP/Data_Predict/Predicted_Result/50_Predict/CF5017_binary.nii.gz
[OK] CF6008: /home/cuixing/MDP/Data_Predict/Predicted_Result/50_Predict/CF6008.nii.gz -> /home/cuixing/MDP/Data_Predict/Predicted_Result/50_Predict/CF6008_binary.nii.gz
[OK] CF6011: /home/cuixing/MDP/Data_Predict/Predicted_Result/50_Predict/CF6011.nii.gz -> /home/cuixing/MDP/Data_Predict/Predicted_Result/50_Predict/CF6011_

## 2.Test some cases and cauculate there dice score as binary label

In [7]:
path = "CF6028"
pred_path = os.path.join("/home/cuixing/MDP/Data_Predict/Predicted_Result/50_Predict/", path + "_binary.nii.gz")
gt_path = os.path.join("/home/cuixing/MDP/Ground_Truth", path, "merged_gt.nii.gz")
pred = nib.load(pred_path).get_fdata()
gt = nib.load(gt_path).get_fdata()

pred_count = np.sum(pred > 0)
pred_zero_count = np.sum(pred == 0)
gt_count = np.sum(gt > 0)
gt_zero_count = np.sum(gt == 0)

print("Foreground voxel count in pred:", pred_count)
print("Background voxel count in pred:", pred_zero_count)
print("Foreground voxel count in gt:", gt_count)
print("Background voxel count in gt:", gt_zero_count)


Foreground voxel count in pred: 1014482
Background voxel count in pred: 59791732
Foreground voxel count in gt: 956944
Background voxel count in gt: 59849270


In [8]:
# cauculate for the total Dice score.
def dice_score(y_true, y_pred):
    intersection = np.sum((y_true > 0) & (y_pred > 0))
    sum_volumes = np.sum(y_true > 0) + np.sum(y_pred > 0)
    return (2.0 * intersection) / (sum_volumes + 1e-6)

dice = dice_score(gt, pred)
print(f"Dice Score: {dice}")

Dice Score: 0.9009103055347242


In [7]:
from scipy.ndimage import label
labeled_array, num_features = label(data_new)

print("Detected ribs (connected components):", num_features)

Detected ribs (connected components): 32


In [8]:
sizes = np.bincount(labeled_array.ravel())
for i in range(1, len(sizes)):
    print(f"Label {i}: Size = {sizes[i]} voxels")

Label 1: Size = 40915 voxels
Label 2: Size = 44723 voxels
Label 3: Size = 48585 voxels
Label 4: Size = 24182 voxels
Label 5: Size = 46037 voxels
Label 6: Size = 48959 voxels
Label 7: Size = 40115 voxels
Label 8: Size = 31574 voxels
Label 9: Size = 14110 voxels
Label 10: Size = 25041 voxels
Label 11: Size = 189 voxels
Label 12: Size = 20694 voxels
Label 13: Size = 4413 voxels
Label 14: Size = 2 voxels
Label 15: Size = 51968 voxels
Label 16: Size = 45877 voxels
Label 17: Size = 43472 voxels
Label 18: Size = 2 voxels
Label 19: Size = 39533 voxels
Label 20: Size = 43925 voxels
Label 21: Size = 29973 voxels
Label 22: Size = 17 voxels
Label 23: Size = 4 voxels
Label 24: Size = 16876 voxels
Label 25: Size = 38394 voxels
Label 26: Size = 5459 voxels
Label 27: Size = 29088 voxels
Label 28: Size = 21469 voxels
Label 29: Size = 24441 voxels
Label 30: Size = 278 voxels
Label 31: Size = 16 voxels
Label 32: Size = 5 voxels


# Seperate Label into each ribs.

In [ ]:
import os
import numpy as np
import nibabel as nib
from glob import glob
from scipy.ndimage import label, center_of_mass

TEST_DIR = "/home/cuixing/MDP/Data_Predict/Test_Data"
BIN_DIR  = "/home/cuixing/MDP/Data_Predict/Predicted_Result/50_Predict"

def process_case(case):
    src = os.path.join(BIN_DIR, f"{case}_binary.nii.gz")
    if not os.path.exists(src):
        print(f"[MISS] {case}: {src}"); return False

    img = nib.load(src)
    data = (img.get_fdata() > 0).astype(np.uint8)

    labeled_array, _ = label(data)
    sizes = np.bincount(labeled_array.ravel())
    if sizes.size <= 1:
        print(f"[EMPTY] {case}"); return False

    comp = sizes[1:]
    k = min(24, comp.size)
    topk = np.argsort(comp)[-k:][::-1]

    filt = np.zeros_like(labeled_array, dtype=np.int16)
    for new_lbl, orig_idx in enumerate(topk, start=1):
        filt[labeled_array == (orig_idx + 1)] = new_lbl

    idxs = np.arange(1, k + 1)
    centers = np.array(center_of_mass(filt, labels=filt, index=idxs))  # (x,y,z)

    x_med = np.median(centers[:, 0])
    left_ids  = np.where(centers[:, 0] <  x_med)[0]
    right_ids = np.where(centers[:, 0] >= x_med)[0]

    left_sorted  = left_ids[np.argsort(centers[left_ids, 2])[::-1]]   # 按 z 从上到下
    right_sorted = right_ids[np.argsort(centers[right_ids, 2])[::-1]]

    final = np.zeros_like(filt, dtype=np.int16)
    # —— 按你之前的编号：右 1..12，左 13..24 ——
    for i, idx in enumerate(right_sorted[:12], start=1):
        final[filt == (idx + 1)] = i            # 右 -> 1..12
    for i, idx in enumerate(left_sorted[:12], start=1):
        final[filt == (idx + 1)] = i + 12       # 左 -> 13..24

    save_dir = os.path.join(BIN_DIR, case)
    os.makedirs(save_dir, exist_ok=True)

    nib.save(nib.Nifti1Image(final, img.affine, img.header), os.path.join(save_dir, "labeled.nii.gz"))

    for i in range(1, 13):
        m = (final == i).astype(np.int16)
        if m.any():
            nib.save(nib.Nifti1Image(m, img.affine, img.header), os.path.join(save_dir, f"rib_left_{i}.nii.gz"))
    for i in range(1, 13):
        m = (final == i + 12).astype(np.int16)
        if m.any():
            nib.save(nib.Nifti1Image(m, img.affine, img.header), os.path.join(save_dir, f"rib_right_{i}.nii.gz"))

    print(f"[OK] {case} -> {save_dir}")
    return True

def process_all():
    case_ids = sorted({os.path.basename(f).split('_')[0] for f in glob(os.path.join(TEST_DIR, "*.nii.gz"))})
    ok = err = 0
    for c in case_ids:
        try:
            ok += 1 if process_case(c) else 0
        except Exception as e:
            err += 1
            print(f"[ERR] {c}: {e}")
    print(f"done ok={ok} err={err}")

if __name__ == "__main__":
    process_all()


[OK] CF5008 -> /home/cuixing/MDP/Data_Predict/Predicted_Result/50_Predict/CF5008
[OK] CF5009 -> /home/cuixing/MDP/Data_Predict/Predicted_Result/50_Predict/CF5009
[OK] CF5015 -> /home/cuixing/MDP/Data_Predict/Predicted_Result/50_Predict/CF5015
[OK] CF5017 -> /home/cuixing/MDP/Data_Predict/Predicted_Result/50_Predict/CF5017
[OK] CF6008 -> /home/cuixing/MDP/Data_Predict/Predicted_Result/50_Predict/CF6008
[OK] CF6011 -> /home/cuixing/MDP/Data_Predict/Predicted_Result/50_Predict/CF6011
[OK] CF6028 -> /home/cuixing/MDP/Data_Predict/Predicted_Result/50_Predict/CF6028
[OK] CF6031 -> /home/cuixing/MDP/Data_Predict/Predicted_Result/50_Predict/CF6031
[OK] CF7011 -> /home/cuixing/MDP/Data_Predict/Predicted_Result/50_Predict/CF7011
[OK] CM5115 -> /home/cuixing/MDP/Data_Predict/Predicted_Result/50_Predict/CM5115
[OK] CM6116 -> /home/cuixing/MDP/Data_Predict/Predicted_Result/50_Predict/CM6116
[OK] CM7104 -> /home/cuixing/MDP/Data_Predict/Predicted_Result/50_Predict/CM7104
[OK] CM7109 -> /home/cuixing

In [ ]:
process_case

In [9]:
# import numpy as np
# import nibabel as nib
# from scipy.ndimage import label, center_of_mass
# import os


# # save path
# save_dir = f"/home/cuixing/MDP/Data_Predict/Predicted_Result/50_Predict/{path}"
# os.makedirs(save_dir, exist_ok=True)

# # Step 1: aggregation area
# labeled_array, num_features = label(data_new)
# sizes = np.bincount(labeled_array.ravel())
# component_sizes = sizes[1:]
# top24_indices = np.argsort(component_sizes)[-24:][::-1]  # volume sort

# # Step 2: remain 24 labels
# filtered_array = np.zeros_like(labeled_array)
# remaining_voxels = {}  # 

# for new_label, orig_label in enumerate(top24_indices, start=1):
#     mask = (labeled_array == (orig_label + 1))
#     filtered_array[mask] = new_label
#     remaining_voxels[new_label] = mask.sum()  #

# # print 24 label voxel
# print("✅ Remaining 24 labels voxel counts:")
# for lbl, vox_count in remaining_voxels.items():
#     print(f"Label {lbl:2d}: {vox_count} voxels")


# # Step 3: centroid
# centers = center_of_mass(filtered_array, labels=filtered_array, index=np.arange(1, 25))
# centers = np.array(centers)

# # Step 4: 
# z_median = np.median(centers[:, 0])
# left_indices = np.where(centers[:, 0] < z_median)[0]
# right_indices = np.where(centers[:, 0] >= z_median)[0]

# # Step 5: 
# left_sorted = left_indices[np.argsort(centers[left_indices, 2])[::-1]]
# right_sorted = right_indices[np.argsort(centers[right_indices, 2])[::-1]]


# # Step 6: anatomically labeled array（1~12：left；13~24：irght）
# final_array = np.zeros_like(filtered_array)

# for i, idx in enumerate(left_sorted):    # 1~12
#     label_val = i + 13
#     final_array[filtered_array == (idx + 1)] = label_val

# for i, idx in enumerate(right_sorted):   # left：13~24
#     label_val = i + 1
#     final_array[filtered_array == (idx + 1)] = label_val

# # Step 7: 保存 labeled.nii.gz
# sorted_img = nib.Nifti1Image(final_array.astype(np.int16), affine=img.affine, header=img.header)
# nib.save(sorted_img, os.path.join(save_dir, "labeled.nii.gz"))
# print("✅ Saved combined anatomical label map: labeled.nii.gz")

# # Step 8: 
# for i in range(1, 13):
#     left_mask = (final_array == i)
#     left_img = nib.Nifti1Image(left_mask.astype(np.int16), affine=img.affine, header=img.header)
#     nib.save(left_img, os.path.join(save_dir, f"rib_left_{i}.nii.gz"))

# for i in range(1, 13):
#     right_mask = (final_array == i + 12)
#     right_img = nib.Nifti1Image(right_mask.astype(np.int16), affine=img.affine, header=img.header)
#     nib.save(right_img, os.path.join(save_dir, f"rib_right_{i}.nii.gz"))

# print("✅ Saved all 24 individual ribs (rib_left_1 ~ rib_right_12)")


✅ Remaining 24 labels voxel counts:
Label  1: 51968 voxels
Label  2: 48959 voxels
Label  3: 48585 voxels
Label  4: 46037 voxels
Label  5: 45877 voxels
Label  6: 44723 voxels
Label  7: 43925 voxels
Label  8: 43472 voxels
Label  9: 40915 voxels
Label 10: 40115 voxels
Label 11: 39533 voxels
Label 12: 38394 voxels
Label 13: 31574 voxels
Label 14: 29973 voxels
Label 15: 29088 voxels
Label 16: 25041 voxels
Label 17: 24441 voxels
Label 18: 24182 voxels
Label 19: 21469 voxels
Label 20: 20694 voxels
Label 21: 16876 voxels
Label 22: 14110 voxels
Label 23: 5459 voxels
Label 24: 4413 voxels
✅ Saved combined anatomical label map: labeled.nii.gz
✅ Saved all 24 individual ribs (rib_left_1 ~ rib_right_12)


In [15]:
print(centers)

[[321.34821429 223.30822814 121.96944273]
 [ 96.05322821 223.20231214 174.68976082]
 [ 78.68572605 233.73570032 112.52310384]
 [ 87.94808524 229.81360645 144.65356127]
 [315.29457026 219.39636419 150.85851298]
 [ 81.11119558 261.56442994  98.26270599]
 [315.54372225 212.69343199 178.45746158]
 [318.30587505 246.8756671  109.69755245]
 [ 90.7164854  283.59063913  81.60437492]
 [101.0913374  214.87107067 201.8503303 ]
 [312.08084385 265.24493461  89.39584651]
 [310.14431942 206.7929364  207.08186175]
 [111.79391271 206.53515551 234.97497941]
 [303.89613986 280.55583358  61.71751243]
 [304.11166117 200.10753575 235.32838284]
 [127.54742223 193.40062298 265.65512559]
 [290.76461683 194.59715233 264.4976474 ]
 [108.94032752 298.2644529   58.00930444]
 [268.08505287 176.96688248 277.27560669]
 [150.14820721 176.70634    280.43181599]
 [278.50711069 289.65376867  40.71207632]
 [134.91148122 301.6080085   37.36286322]
 [241.62758747 275.66275875  15.89210478]
 [168.61318831 280.1969182   15.61

In [16]:
x_median

133.3115019999642

In [18]:
left_sorted


array([ 2,  5,  8, 17, 21, 23, 22, 20, 13, 10,  7,  0])